My_Market/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import My_Market.settings as settings
from product.views import *

urlpatterns = i18n_patterns(
    path('', HomeView.as_view(), name='home'),
    path('change-lang/', ChangeLanguageView.as_view(), name='change_lang'),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('customer/', include('customer.urls')),
    path('order/', include('order.urls')),
    path('product-api/', include('product.api_urls')),
    path('customer-api/', include('customer.api_urls')),
    path('order-api/', include('order.api_urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=True,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path

from .views import *

app_name = 'customer'
urlpatterns = [
    path('register/', CustomerRegisterView.as_view(), name='customer_register'),
    path('login/', CustomerLoginView.as_view(), name='customer_login'),
    path('logout/', CustomerLogoutView.as_view(), name='customer_logout'),
    path('profile/', CustomerProfileView.as_view(), name='customer_profile'),
    path('profile/update/', CustomerProfileUpdateView.as_view(), name='customer_profile_update'),
    path('add-address/', AddressCreateView.as_view(), name='add_address'),
    path('update-address/<int:pk>/', AddressUpdateView.as_view(), name='update_address'),
    path('delete-address/<int:pk>/', AddressDeleteView.as_view(), name='delete_address'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('favorites/', FavoritesView.as_view(), name='favorites'),
    path('order-history/', OrderListView.as_view(), name='order_history'),
]

order/urls.py
from django.urls import path

from .views import *

app_name = 'order'
urlpatterns = [
    path('', OrderDetailView.as_view(), name='order_detail'),
    path('paid/', PaidOrderDetailView.as_view(), name='paid_order_detail'),
    path('canceled/', CanceledOrderDetailView.as_view(), name='canceled_order_detail'),
    path('add/<int:pk>/', OrderAddView.as_view(), name='order_add'),
    path('add-off-code/', OffCodeAddView.as_view(), name='off_code_add'),
    path('add-quantity/<int:pk>/', AddQuantityView.as_view(), name='add_quantity'),
    path('remove-quantity/<int:pk>/', RemoveQuantityView.as_view(), name='remove_quantity'),
    path('delete-order-item/<int:pk>/', RemoveOrderItemView.as_view(), name='remove_order_item'),
    path('create-order/<int:pk>/', CreateOrderView.as_view(), name='create_order'),
    path('remove-off-code/<int:pk>/', RemoveOffCodeView.as_view(), name='remove_off_code'),
    path('select-address/', SelectAddress.as_view(), name='select_address'),
    path('add-address/', AddressCreateView.as_view(), name='add_address'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('cancel-order/', CancelOrderView.as_view(), name='cancel_order'),
]

product/forms.py
from django import forms
from .models import *


class CommentForm(forms.ModelForm):
    rate = forms.IntegerField(
        required=False,
        validators=[rate_validator],
    )

    class Meta:
        model = Comment
        fields = ['comment', 'rate']


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']


class SearchForm(forms.Form):
    key = forms.CharField(
        max_length=30,
    )

templates/base/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
{% if language == 'fa' %}
    <html lang="fa" dir="rtl">
{% else %}
    <html lang="en">
{% endif %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block Title %}{% endblock %}</title>
    <link rel="icon" type="image/gif/png" href="{% static 'base/img/logo_title.png' %}">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css"/>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css"/>
    <link rel='stylesheet' href='https://sachinchoolur.github.io/lightslider/dist/css/lightslider.css'>
    {% block ExtraHead %}{% endblock %}
</head>
<style>
    body, h1, h2, h3, h4, h5 {
    {% if language == 'fa' %}
        font-family: IRANSans;
    {% else %}
        font-family: "Raleway", sans-serif
    {% endif %}
    }

    body {
        background-color: var(--asli);
    }

    #middle-search input {
        border-radius: 5px;
        border: 8px solid transparent;
        background-color: #cfcfcf;
        text-align: center;
    }

    #middle-search input:focus {
        background-color: white;
    }

    #middle-search button {
        border-radius: 5px;
        border: 8px solid transparent;
        background-color: green;
        color: white;
        text-align: center;
        width: 100px;
        height: auto;
    }

    @media screen and (max-width: 780px) {
        #middle-search {
            display: none;

        }
    }
</style>
{% block ExtraStyle %}{% endblock %}
<body>
<div class="container-fluid">

    {% block OffCode %}{% endblock %}

    {# header#}
    <div class="row"
         style="height: 80px;background-color: var(--header);padding-right: 0;padding-left: 2.5rem;direction: ltr">

        <div class="col-2 col-md-1 col-lg-1" style="text-align: center">
            <a href="{% url 'order:order_detail' %}">
                <img style="margin-top: 0.5rem;margin-bottom: 0.3rem;width: 45%;height: auto"
                     src="{% static 'base/img/card.png' %}"/>
            </a>
            <p>{% trans "Cart" %}</p>

        </div>
        <div class="col-2 col-md-1 col-lg-1" style="text-align: center">
            {% block Login %}
                {% if request.user.is_authenticated %}
                    {% include 'base/logout.html' %}
                {% elif not request.user.is_authenticated %}
                    {% include 'base/login.html' %}
                {% endif %}
            {% endblock %}
        </div>
        <div class="col-1 col-md-5 col-lg-7" style="text-align: center;padding-top: 1.5rem">
            <form id="middle-search" method="post" action="{% url 'product_search' %}">
                {% csrf_token %}

                <input {% if language == 'fa' %}style="direction: rtl" {% endif %}type="text" name="key" maxlength="30"
                       required="" id="id_key"
                       placeholder="{% trans 'search...' %}">
                <button type="submit">{% trans 'Search' %}</button>
            </form>
        </div>
        <div class="col-7 col-md-5 col-lg-3" style="padding-right: 0;padding-left: 5rem">

            <a href={% url 'home' %}>
                <img style="width: 100%; height: auto;margin-right: 0;margin-bottom: 0.3rem;margin-top: 0"
                     src="{% static 'base/img/logo.png' %}">
            </a>

        </div>

    </div>
    {% block Navbar %}
        <div class="row base-nav" {% if not messages %}
             style="margin-bottom: 3rem"{% endif %}>{% include 'base/navbar.html' with category=category %}</div>
    {% endblock %}
    {% block Messages %}
        <div class="row" style="margin-bottom: 3rem">{% include 'base/message.html' %}</div>{% endblock %}
    {# header#}

    {#body#}
    {% block Body %}{% endblock %}
    {#body#}


    {#    footer#}
    <div class="row" style=" background-color: var(--footer);text-align: center;margin-top: 9rem">
        <div class="row" style="margin-top: 5rem;margin-bottom: 2rem;padding-left: 3rem;padding-right: 3rem">
            <div class="col-12 col-sm-6 col-lg-3" style="text-align: center;margin-bottom: 2rem">
                <img src="{% static 'base/img/trust.svg' %}">
                <p>{% trans 'Online support' %}</p>
            </div>
            <div class="col12 col-sm-6 col-lg-3" style="text-align: center;margin-bottom: 2rem">
                <img src="{% static 'base/img/ert.svg' %}">
                <p>{% trans 'Direct link' %}</p>
            </div>
            <div class="col-12 col-sm-6 col-lg-3" style="text-align: center;margin-bottom: 2rem">
                <img src="{% static 'base/img/taq.svg' %}">
                <p>{% trans 'Money back guarantee' %}</p>
            </div>
            <div class="col-12 col-sm-6 col-lg-3" style="text-align: center;margin-bottom: 2rem">
                <img src="{% static 'base/img/par.svg' %}">
                <p>{% trans 'Secure payment' %}</p>
            </div>

        </div>
        <hr>
        <div class="row" style="margin-bottom: 3rem;margin-top: 2rem">
            <div class="col-4"></div>
            <div class="col-2">
                <a href="https://github.com/amirmasoud1420">
                    <img src="https://img.icons8.com/dusk/64/000000/github.png"/>
                </a>
            </div>
            <div class="col-2">
                <a href="https://www.linkedin.com/in/amirmasoud-talebnia-071b55218/">
                    <img src="https://img.icons8.com/dusk/64/000000/linkedin.png"/>
                </a>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
    {#    footer#}
</div>
<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
</body>

</html>

templates/base/login.html
{% load i18n %}
{% load static %}
<a href={% url 'customer:customer_login' %}>
    {#                                <img style="margin-top: 0.7rem" src="https://img.icons8.com/pastel-glyph/50/000000/user-male--v1.png"/>#}
    <img style="margin-top: 0.3rem;margin-bottom: 0.3rem;width: 45%;height: auto"
         src="{% static 'base/img/profileicon.png' %}"/>

</a>
<p>{% trans "Login\Register" %}</p>

templates/base/logout.html
{% load i18n %}
{% load static %}

<a href={% url 'customer:customer_logout' %}>
    <img style="margin-top: 0.3rem;margin-bottom: 0.3rem;width: 45%;height: auto"
         src="https://img.icons8.com/ios-filled/100/000000/logout-rounded.png"/>

</a>
<p>{% trans "Logout" %}</p>

templates/base/message.html
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
{% if messages %}
    {% for msg in messages %}
        <h4 style="text-align: center" {% if msg.tags %} class="message alert alert-{{ msg.tags }}" {% endif %} >{{ msg }}</h4>
    {% endfor %}
{% endif %}

<script>
    $(document).ready(function () {
        // messages timeout for 10 sec
        setTimeout(function () {
            $('.message').fadeOut('slow');
        }, 5000); // <-- time in milliseconds, 1000 =  1 sec

        // delete message
        {#$('.del-msg').live('click', function () {#}
        {#    $('.del-msg').parent().attr('style', 'display:none;');#}
        //})
    });
</script>

templates/base/nav_category.html
<style>
    #cat-ul {
        width: auto;
    }
</style>
<ul id='cat-ul'>
    {% for i in category %}
        <li><a href="{% url 'menu_item_category' i.id %}">
            {% if language == 'fa' %}
                {% if i.name_fa %}
                    {{ i.name_fa }}
                {% else %}
                    {{ i.name }}
                {% endif %}
            {% else %}
                {{ i.name }}
            {% endif %}

        </a>
            {% include 'base/nav_category.html' with category=i.category_set.all %}
        </li>

    {% endfor %}
</ul>

templates/base/navbar.html
{% load static %}
{% load i18n %}

<style>
    @import url("https://fonts.googleapis.com/css?family=Roboto:400,400i,700");

    .my-nav {
        padding: 0;
        margin-bottom: 0;


    }

    .my-nav ul {

        background-color: darkslategray;
        margin-bottom: 0;
        display: flex;
    {#background: #2F343D;#} padding-bottom: 0;
        padding-top: 0;
    {#border-right: 5px solid #3F83EF;#} width: 100%;
        transition: 0.5s;
        overflow: hidden;

    }

    .my-nav ul li {
        text-align: center;
        display: flex;
        list-style: none;
        padding: 15px;
        padding-right: 2rem;
        color: white;
        font-size: 15px;

        cursor: pointer;
        position: relative;
        transition: 0.5s;


    }

    .my-nav ul li:hover {
        transition: 0s;
        z-index: 2;

    }

    .my-nav ul li.active:before {
        content: '';
        position: absolute;
        top: -20px;
        right: 20px;
        width: 20px;
        height: 20px;
        background: transparent;

    }

    .my-nav ul li.active:after {
        content: '';
        position: absolute;
        bottom: -20px;
        right: 20px;
        width: 20px;
        height: 20px;
        background: transparent;
        border-radius: 50%;


    }


    .my-nav ul:hover {
        width: 100%;
    }

    .my-nav ul li a {
        font-size: 1rem;
        text-decoration: none;
        color: white;
    }

    .my-nav ul li:hover {
        color: yellow;
    }

    .my-nav ul li a:hover {
        text-decoration: none;
        color: yellow
    }

    .my-nav ul ul {
        display: none;
    }

    .my-nav ul li:hover > ul {
        display: block;
    }
</style>

<div class="container-fluid my-nav">
    <ul>
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'customer:customer_profile' %}">{% trans 'Profile' %}</a></li>
        <li><a href="{% url 'change_lang' %}">
            {% if language == 'fa' %}
                تغییر زبان &nbsp;  (English)
            {% else %}
                change language &nbsp;(فارسی)
            {% endif %}
        </a></li>
        <li>{% trans 'Category' %}
            {% include 'base/nav_category.html' with category=category %}
        </li>

    </ul>
</div>

<script>
    let items = document.querySelectorAll('li');

    items.forEach(item => {
        item.addEventListener('click', () => {
            items.forEach(item => item.classList.remove('active'))
            item.classList.add('active')

        })
    })
</script>

templates/base/pagination.html
{% load i18n %}
<style>
    .pagination{
        justify-content: center;
    }
</style>
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if menu_items.has_previous %}
            <li class="page-item"><a class="page-link"
                                     href="?page={{ menu_items.previous_page_number }}">{% trans 'Previous' %}</a>
            </li>
            <li class="page-item"><a class="page-link"
                                     href="?page={{ menu_items.previous_page_number }}">{{ menu_items.previous_page_number }}</a>
            </li>
        {% endif %}


        <li class="page-item"><a style="background-color: blue;color: white" class="page-link"
                                 href="?page={{ menu_items.number }}">{{ menu_items.number }}</a>
        </li>


        {% if menu_items.has_next %}
            <li class="page-item"><a class="page-link"
                                     href="?page={{ menu_items.next_page_number }}">{{ menu_items.next_page_number }}</a>
            </li>
            <li class="page-item"><a class="page-link"
                                     href="?page={{ menu_items.next_page_number }}">{% trans 'Next' %}</a></li>

        {% endif %}


    </ul>
</nav>