My_Market/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import My_Market.settings as settings
from product.views import *

urlpatterns = i18n_patterns(
    path('', HomeView.as_view(), name='home'),
    path('change-lang/', ChangeLanguageView.as_view(), name='change_lang'),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('customer/', include('customer.urls')),
    path('order/', include('order.urls')),
    path('product-api/', include('product.api_urls')),
    path('customer-api/', include('customer.api_urls')),
    path('order-api/', include('order.api_urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=True,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path

from .views import *

app_name = 'customer'
urlpatterns = [
    path('register/', CustomerRegisterView.as_view(), name='customer_register'),
    path('login/', CustomerLoginView.as_view(), name='customer_login'),
    path('logout/', CustomerLogoutView.as_view(), name='customer_logout'),
    path('profile/', CustomerProfileView.as_view(), name='customer_profile'),
    path('profile/update/', CustomerProfileUpdateView.as_view(), name='customer_profile_update'),
    path('add-address/', AddressCreateView.as_view(), name='add_address'),
    path('update-address/<int:pk>/', AddressUpdateView.as_view(), name='update_address'),
    path('delete-address/<int:pk>/', AddressDeleteView.as_view(), name='delete_address'),
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('favorites/', FavoritesView.as_view(), name='favorites'),
    path('order-history/', OrderListView.as_view(), name='order_history'),
]

order/urls.py
from django.urls import path

from .views import *

app_name = 'order'
urlpatterns = [
    path('', OrderDetailView.as_view(), name='order_detail'),
    path('paid/', PaidOrderDetailView.as_view(), name='paid_order_detail'),
    path('canceled/', CanceledOrderDetailView.as_view(), name='canceled_order_detail'),
    path('add/<int:pk>/', OrderAddView.as_view(), name='order_add'),
    path('add-off-code/', OffCodeAddView.as_view(), name='off_code_add'),
    path('add-quantity/<int:pk>/', AddQuantityView.as_view(), name='add_quantity'),
    path('remove-quantity/<int:pk>/', RemoveQuantityView.as_view(), name='remove_quantity'),
    path('delete-order-item/<int:pk>/', RemoveOrderItemView.as_view(), name='remove_order_item'),
    path('create-order/<int:pk>/', CreateOrderView.as_view(), name='create_order'),
    path('remove-off-code/<int:pk>/', RemoveOffCodeView.as_view(), name='remove_off_code'),
    path('select-address/', SelectAddress.as_view(), name='select_address'),
    path('add-address/', AddressCreateView.as_view(), name='add_address'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('cancel-order/', CancelOrderView.as_view(), name='cancel_order'),
]

customer/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.models import *


# Create your models here.
class Customer(BaseModel, TimestampMixin):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )
    image = models.FileField(
        verbose_name=_('Customer image'),
        help_text=_('customer image'),
        upload_to='customer/customer/images/',
        null=True,
        blank=True,
        default='customer/customer/images/default.jpg'
    )

    def my_delete(self):
        super().my_delete()
        self.user.is_active = False
        self.user.save()
        for i in self.address_set.all():
            i.delete_time_stamp = timezone.now()
            i.is_deleted = True
            i.save()

    def __str__(self):
        return f"{self.id}# {self.user.phone}"

    class Meta:
        verbose_name = _('Customer')
        verbose_name_plural = _('Customers')


class Address(BaseModel, TimestampMixin):
    owner = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
    )
    state = models.CharField(
        verbose_name=_("The State"),
        help_text=_("The State"),
        max_length=50,
    )
    city = models.CharField(
        verbose_name=_("The City"),
        help_text=_("The City"),
        max_length=50,
    )
    postal_code = models.CharField(
        verbose_name=_("The Postal code"),
        help_text=_("The Postal code"),
        max_length=10,
    )
    detail = models.TextField(
        verbose_name=_("Detail"),
        help_text=_("detail"),
    )
    lat = models.FloatField(
        verbose_name=_("Latitude"),
        help_text=_("latitude"),
    )
    lng = models.FloatField(
        verbose_name=_("Longitude"),
        help_text=_("longitude"),
    )

    def __str__(self):
        return f"{self.id}#{self.owner.user.phone} : {self.state}-{self.city}"

    class Meta:
        verbose_name = _('Address')
        verbose_name_plural = _('Addresses')

product/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.models import *
from .validators import *
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager
from django.db.models import Avg, Min, Max
from customer.models import *


# Create your models here.


class Category(BaseModel, TimestampMixin):
    name = models.CharField(
        max_length=50,
        verbose_name=_('Name'),
        help_text=_('Category Name'),
    )
    name_fa = models.CharField(
        max_length=50,
        verbose_name=_('PersianName'),
        null=True,
        blank=True,
    )
    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    is_sub_category = models.BooleanField(
        verbose_name=_('Is sub category?'),
        help_text=_('Is sub category? or main?'),
        default=False,
    )

    def my_delete(self):
        super().my_delete()
        for i in self.category_set.all():
            i.my_delete()

    def __str__(self):
        return f"{self.id}# {self.name}"

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class Discount(BaseModel, TimestampMixin):
    is_percent = models.BooleanField(
        default=False,
        verbose_name=_('Is Percent?'),
        help_text=_('Do you want to enter a percentage?'),
    )
    price = models.IntegerField(
        verbose_name=_('Discount Price'),
        help_text=_('Enter the discount price'),
        validators=[price_validator],
        default=0,
    )
    percent = models.FloatField(
        verbose_name=_('Discount Percent'),
        help_text=_('Enter the discount percent'),
        validators=[percent_validator],
        default=0,
    )
    max = models.IntegerField(
        null=True,
        blank=True,
        verbose_name=_('Max Discount Price'),
        help_text=_('Enter the max discount price'),
        validators=[price_validator],
    )
    expire_date_time = models.DateTimeField(
        verbose_name=_('Expire Date'),
        help_text=_('Enter the expire date'),
    )

    def is_expired(self):
        if self.is_deleted:
            return True
        if timezone.now() > self.expire_date_time:
            return True
        return False

    def final_price(self, price):
        if self.is_percent:
            discount = (price * self.percent) // 100
            if self.max:
                if discount > self.max:
                    return price - self.max
                else:
                    return price - discount
            else:
                return price - discount
        else:
            if price > self.price:
                return price - self.price
            else:
                return 0

    def __str__(self):
        if self.is_percent:
            return f"{self.id}# {self.percent}% , max = {self.max} , expire-date = {self.expire_date_time} , {self.is_expired()}"
        else:
            return f"{self.id}# {self.price}$ , max = {self.max} , expire-date = {self.expire_date_time} , {self.is_expired()}"

    class Meta:
        verbose_name = _('Discount')
        verbose_name_plural = _('Discounts')


class OffCode(Discount):
    code = models.CharField(
        verbose_name=_('Off Code'),
        max_length=14,
        validators=[off_code_validator],
        help_text=_('Enter the off code'),
    )

    class Meta:
        verbose_name = _('OffCode')
        verbose_name_plural = _('OffCodes')


""""
    menu item classes
"""


class Brand(BaseModel, TimestampMixin):
    name = models.CharField(
        max_length=30,
        verbose_name=_('brand name'),
        help_text=_('Enter the brand name'),
        # validators=[menu_item_name_validator],
    )
    name_fa = models.CharField(
        max_length=50,
        verbose_name=_('PersianName'),
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = _('Brand')
        verbose_name_plural = _('Brands')


class Image(BaseModel, TimestampMixin):
    image = models.FileField(
        verbose_name=_('menu item image'),
        help_text=_('Enter your image'),
        upload_to='product/menu_items/images/',
    )
    menu_item = models.ForeignKey(
        'MenuItem',
        on_delete=models.CASCADE,
        verbose_name=_('menu item for this image'),
        help_text=_('Enter the menu item for this image'),
    )

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Images')


class Specification(BaseModel, TimestampMixin):
    name = models.CharField(
        max_length=200,
        verbose_name=_('Specification name'),
        help_text=_('Enter the Specification name'),
    )
    name_fa = models.CharField(
        max_length=200,
        verbose_name=_('PersianName'),
        null=True,
        blank=True,
    )
    value = models.CharField(
        max_length=200,
        verbose_name=_('Specification Value'),
        help_text=_('Enter the Specification value'),
    )
    value_fa = models.CharField(
        max_length=200,
        verbose_name=_('PersianValue'),
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"{self.id}# {self.name} : {self.value}"

    class Meta:
        verbose_name = _('Specification')
        verbose_name_plural = _('Specifications')


class VariableSpecification(BaseModel, TimestampMixin):
    name = models.CharField(
        max_length=200,
        verbose_name=_('Specification name'),
        help_text=_('Enter the Specification name'),
    )
    value = models.CharField(
        max_length=200,
        verbose_name=_('Specification Value'),
        help_text=_('Enter the Specification value'),
    )

    def __str__(self):
        return f"{self.id}# {self.name} : {self.value}"

    class Meta:
        verbose_name = _('VariableSpecification')
        verbose_name_plural = _('VariableSpecifications')


class MenuItem(BaseModel, TimestampMixin):
    name = models.CharField(
        max_length=50,
        verbose_name=_('menu item name'),
        help_text=_('Enter the Menu items name'),

    )
    name_fa = models.CharField(
        max_length=50,
        verbose_name=_('PersianName'),
        null=True,
        blank=True,
    )
    category = models.ManyToManyField(
        Category,
        verbose_name=_('menu item category'),
        help_text=_('Choose the menu item stock'),
    )
    brand = models.ForeignKey(
        Brand,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_('menu item brand'),
        help_text=_('Choose the menu item brand'),
    )
    specifications = models.ManyToManyField(
        Specification,
        related_name='menu_items',
    )
    description = RichTextUploadingField(
        verbose_name=_('menu item description'),
        help_text=_('Enter the menu item description'),
        null=True,
        blank=True,
    )
    description_fa = RichTextUploadingField(
        verbose_name=_('PersianDescription'),
        null=True,
        blank=True,
    )

    status = models.BooleanField(
        verbose_name=_('variant status'),
        help_text=_('has variant?'),
        default=False,
    )
    variable_specification_name = models.CharField(
        verbose_name=_('Variable Specification name'),
        help_text=_('variable specification name'),
        max_length=50,
        null=True,
        blank=True,
    )
    variable_specification_name_fa = models.CharField(
        verbose_name=_('Variable Specification persian name'),
        max_length=50,
        null=True,
        blank=True,
    )
    tags = TaggableManager(
        verbose_name=_('Similar specification'),
        help_text=_('for similar product'),
        blank=True,
    )
    favorites_customers = models.ManyToManyField(
        Customer,
        blank=True,
        related_name='favorites',
    )
    sell = models.IntegerField(default=0, verbose_name=_('sell count'))

    def my_delete(self):
        super().my_delete()
        for i in self.menuitemvariant_set.all():
            i.delete_time_stamp = timezone.now()
            i.is_deleted = True
            i.save()
        for i in self.comment_set.all():
            i.delete_time_stamp = timezone.now()
            i.is_deleted = True
            i.save()

    def average_rate(self):
        data = Comment.objects.filter(is_reply=False, menu_item=self).aggregate(avg=Avg('rate'))
        rate = 0
        if data['avg']:
            rate = round(data['avg'], 1)
        return rate

    def __str__(self):
        return f"{self.id}#   {self.name} "

    class Meta:
        verbose_name = _('MenuItem')
        verbose_name_plural = _('MenuItems')


class MenuItemVariant(BaseModel, TimestampMixin):
    menu_item = models.ForeignKey(
        MenuItem,
        on_delete=models.CASCADE,
    )

    price = models.IntegerField(
        verbose_name=_('menu item price'),
        help_text=_('Enter the menu item price'),
        validators=[price_validator],
    )
    count = models.IntegerField(
        verbose_name=_('menu item stock'),
        help_text=_('Enter the menu item stock'),
        validators=[price_validator],
        default=0,
    )
    discount = models.ForeignKey(
        Discount,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_('menu item discount'),
        help_text=_('Enter the menu item discount'),
    )
    variable_specification_value = models.CharField(
        verbose_name=_('Variable Specification Value'),
        help_text=_('variable specification value'),
        max_length=50,
        default=_('Not entered'),
    )
    variable_specification_value_fa = models.CharField(
        verbose_name=_('Variable Specification persian Value'),
        max_length=50,
        null=True,
        blank=True,
    )

order/forms.py
from django import forms
from .models import *

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order

templates/customer/address.html
{% load i18n %}
<style>
    .address-card {
        width: 80%;
        height: 100px;
        background-color: darkslategray;
        margin-bottom: 2rem;
        margin-left: auto;
        margin-right: auto;

        border: solid 1px yellow;
        border-radius: 10rem;
        padding-top: 0.3rem;
        padding-bottom: 0.3rem;
    }
</style>
<div class="address-card">
    <b style="text-align: center;color: white">{{ address.state }}-{{ address.city }}</b>
    <hr style="color: yellow">
    <a href="{% url 'customer:update_address' pk=address.id %}" class="btn btn-primary"
       style="height: 30px">{% trans 'update' %}</a>
    <a href="{% url 'customer:delete_address' pk=address.id %}" class="btn btn-danger"
       style="height: 30px">{% trans 'delete' %}</a>
</div>

templates/customer/base_profile.html
{% extends 'base/base.html' %}
{% load static %}
{% load i18n %}
{% block Title %}{% trans 'profile' %}{% endblock %}
{% block ExtraHead %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
{% endblock %}
{% block ExtraStyle %}
    <style>
        .my-items {
            background-color: yellowgreen;
            height: 70vh;
            border-radius: 0 15px 15px 0;


        }

        .img-box {
            background-color: white;
            height: 40%;
            border-radius: 15px;
            text-align: center;


        }

        .my-roes {
            height: 10%;

            text-align: center;
            width: 100%;
            border-radius: 15px;
            padding-top: 1rem;
            margin: auto;
            color: white;

        }

        .my-roes:hover {
            background-color: darkolivegreen;
        }

        .my-roes a {
            color: white;
            text-decoration-line: none;
        }
    </style>
    {% block ExtraStyle1 %}{% endblock %}
{% endblock %}
{% block Body %}
    <div class="row">
        <div class="col-12 col-sm-3 col-md-2 my-items">
            <div class=" img-box">
                <img style="height: 80%; width: auto; max-width: 90%"
                     src="{% static customer.image %}">
            </div>
            <div class="row my-roes">
                <a href="#">{% trans 'Dashboard' %}</a>
            </div>
            <div class="row my-roes">
                <a href="{% url 'customer:customer_profile_update' %}">{% trans 'Update Profile' %}</a>
            </div>
            <div class="row my-roes">
                <a href="{% url 'customer:add_address' %}">{% trans 'Add Address' %}</a>
            </div>
            <div class="row my-roes">
                <a href="{% url 'customer:change_password' %}">{% trans 'Change Password' %}</a>
            </div>
            <div class="row my-roes">
                <a href="{% url 'customer:favorites' %}">{% trans 'Favorites' %}</a>
            </div>
            <div class="row my-roes">
                <a>{% trans 'Orders' %}</a>
            </div>
        </div>


        <div class="col-12 col-sm-9 col-md-10" id="content">
            {% block Profile %}{% endblock %}
        </div>
    </div>
{% endblock %}

templates/customer/login.html
{% extends 'base/base.html' %}
{% load static %}
{% load i18n %}
{% block Title %}{% trans 'Login' %}{% endblock %}
{% block ExtraHead %}
    <link rel="stylesheet" href="{% static 'customer/css/register.css' %}">
{% endblock %}
{% block Body %}
    <div class="my-form">
        <form method="post" novalidate style="direction: ltr">
            {% csrf_token %}
            {#            {{ form.as_p }}#}

            {#            <label for="username">{% trans 'username' %}</label>#}
            {#            {{ form.username }}<br><br>#}

            <input id="username" type="text" maxlength="50" name="username"
                   placeholder={% trans 'PhoneNumber or Email' %}><br><br>

            {#            <label for="password">{% trans 'password' %}</label>#}

            <input id="password" type="password" name="password" placeholder={% trans 'password' %}><br><br>

            {#            {{ form.password }}<br><br>#}
            <button type="submit">{% trans 'Login' %}</button>
        </form>
        <p id="rl">{% trans "Don't have an account?  " %}<a
                href={% url 'customer:customer_register' %}>{% trans 'Register' %}</a>
        </p>
    </div>
{% endblock %}

templates/customer/orders.html
{% extends 'customer/profile.html' %}
{% load static %}
{% load i18n %}
{% block Title %}{% trans 'Orders History' %}{% endblock %}
{% block ExtraStyle1 %}
    <style>
        .modal-img-box {
            height: 70px;
            width: 70px;
        }

        .modal-img {
            height: 60px;
            width: auto;
            max-width: 60px;
        }
    </style>
{% endblock %}
{% block Profile %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">{% trans 'Number' %}</th>
            <th scope="col">{% trans 'DateTime' %}</th>
            <th scope="col">{% trans 'Status' %}</th>
            <th scope="col">{% trans 'FinalPrice' %}</th>
            <th scope="col">{% trans 'Detail' %}</th>
        </tr>
        </thead>
        <tbody>
        {% for i in orders %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ i.create_time_stamp }}</td>
                <td>
                    {% if i.status == 'd' %}
                        {% trans 'during' %}
                    {% elif i.status == 'p' %}
                        {% trans 'paid' %}
                    {% else %}
                        {% trans 'canceled' %}
                    {% endif %}
                </td>
                <td>
                    {% if i.status == 'd' %}
                        {{ i.final_price }}
                    {% else %}
                        {{ i.paid_price }}
                    {% endif %}
                </td>
                <td>
                    <!-- Button trigger modal -->
                    <a href="#" data-bs-toggle="modal" data-bs-target="#s{{ i.id }}">
                        {% trans 'detail' %}
                    </a>

                    <!-- Modal -->
                    <div class="modal fade" id="s{{ i.id }}" tabindex="-1" aria-labelledby="exampleModalLabel"
                         aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">{% trans 'order detail' %}</h5>
                                </div>
                                <div class="modal-body">
                                    {% for o in i.ordermenuitem_set.all %}
                                        <div class="row">
                                            <div class="col-4 modal-img-box">
                                                <img class="modal-img"
                                                     src="{{ o.menu_item_variant.menu_item.image_set.last.image.url }}">
                                            </div>
                                            <div class="col-4">
                                                <p style="margin-top: 1rem">

                                                    {% if language == 'fa' %}
                                                        {% if o.menu_item_variant.menu_item.name_fa %}
                                                            {{ o.menu_item_variant.menu_item.name_fa }}
                                                        {% else %}
                                                            {{ o.menu_item_variant.menu_item.name }}
                                                        {% endif %}
                                                    {% else %}
                                                        {{ o.menu_item_variant.menu_item.name }}
                                                    {% endif %}

                                                </p>
                                            </div>
                                            <div class="col-4">
                                                <p style="margin-top: 1rem">
                                                    {% trans 'quantity : ' %}{{ o.quantity }}</p>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary"
                                            data-bs-dismiss="modal">{% trans 'Close' %}
                                    </button>

                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="row pag">
        {% include 'base/pagination.html' with menu_items=page_obj %}
    </div>
{% endblock %}

templates/customer/profile.html
{% extends 'base/base.html' %}
{% load static %}
{% load i18n %}
{% block Title %}{% trans 'Profile' %}{% endblock %}
{% block ExtraStyle %}
    <style>


        .profile {
            margin: 20px 0;
        }


        .profile-sidebar {
            padding: 20px 0 10px 0;
            background: #fff;
        }

        .profile-userpic img {
            text-align: center;
            float: none;
            margin: auto;
            width: 78%;
            height: 78%;
            -webkit-border-radius: 50% !important;
            -moz-border-radius: 50% !important;
            border-radius: 50% !important;
        }

        .profile-usertitle {
            text-align: center;
            margin-top: 20px;
        }

        .profile-usertitle-name {
            color: #5a7391;
            font-size: 20px;
            font-weight: 600;
            margin-bottom: 7px;
        }


        /* Profile Content */
        .profile-content {
            padding: 20px;
            background: #fff;
            min-height: 460px;
        }


        a, button, code, div, img, input, label, li, p, pre, select, span, svg, table, td, textarea, th, ul {
            -webkit-border-radius: 0 !important;
            -moz-border-radius: 0 !important;
            border-radius: 0 !important;
        }


        .portlet {
            margin-top: 0;
            margin-bottom: 25px;
            padding: 0;
            border-radius: 4px;
        }

        .portlet.bordered {
            border-left: 2px solid #e6e9ec !important;
        }

        .portlet.light {
            padding: 12px 20px 15px;
            background-color: #fff;
        }

        .portlet.light.bordered {
            border: 1px solid #e7ecf1 !important;
        }


        .profile-desc-title {
            color: #7f90a4;
            font-size: 17px;
            font-weight: 600;
        }

        .profile-desc-text {
            color: #7e8c9e;
            font-size: 14px;
        }

        .margin-top-20 {
            margin-top: 20px !important;
        }

        .cus-btn {
            width: 200px;
            margin: auto;
            margin-top: 4rem;
        }
    </style>
    {% block ExtraStyle1 %}{% endblock %}
{% endblock %}
{% block Body %}
    {% if language == 'fa' %}
        <div class="container" dir="rtl">
    {% else %}
        <div class="container">
    {% endif %}

<div class="row profile">
    <div class="col-md-3">
        <div class="profile-sidebar">
            <!-- SIDEBAR USERPIC -->
            <div style="margin: auto;text-align: center" class="profile-userpic">
                <img style="margin: auto" src={% static customer.image %}
                        class="img-responsive" alt="">
            </div>
            <!-- END SIDEBAR USERPIC -->
            <!-- SIDEBAR USER TITLE -->
            <div class="profile-usertitle">
                <div class="profile-usertitle-name">
                    {{ customer.user.first_name }}{% trans ' ' %}{% trans ' ' %}{{ customer.user.last_name }}
                </div>

            </div>


            <div class="portlet light bordered">

                <div>
                    <h4 class="profile-desc-title">{% trans 'Phone Number' %}</h4>
                    <p class="profile-desc-text">{{ customer.user.phone }}</p>
                    <h4 class="profile-desc-title">{% trans 'Email' %}</h4>
                    <p class="profile-desc-text">{{ customer.user.email }}</p>

                </div>

            </div>
            <div class="row">
                <a class="btn btn-success cus-btn" style="margin: auto"
                   href={% url 'customer:customer_profile' %}>{% trans 'Dashboard' %}</a>
                <p></p>
                <a class="btn btn-success cus-btn" style="margin: auto"
                   href={% url 'customer:customer_profile_update' %}>{% trans 'Update Profile' %}</a>
                <p></p>
                <a class="btn btn-success cus-btn" style="margin: auto"
                   href={% url 'customer:add_address' %}>{% trans 'Add Address' %}</a>
                <p></p>
                <a class="btn btn-success cus-btn" style="margin: auto;text-align: center"
                   href={% url 'customer:change_password' %}>{% trans 'Change Password' %}</a>
                <p></p>
                <a class="btn btn-success cus-btn" style="margin: auto;text-align: center"
                   href="{% url 'customer:favorites' %}">{% trans 'Favorites' %}</a>
                <p></p>
                <a class="btn btn-success cus-btn" style="margin: auto;text-align: center"
                   href="{% url 'customer:order_history' %}">{% trans 'Orders History' %}</a>
            </div>

        </div>
    </div>
    <div class="col-md-9">
        {% block Profile %}
            <div class="profile-content">
                <div class="row">
                    {% for add in customer.address_set.all %}
                        <div class="col-12 col-lg-6" style="text-align: center;">

                            {% include 'customer/address.html' with address=add %}

                        </div>
                    {% endfor %}

                </div>
            </div>
        {% endblock %}
    </div>
</div>
</div>
{% endblock %}

templates/customer/register.html
{% extends 'base/base.html' %}
{% load static %}
{% load i18n %}
{% block Title %}{% trans 'Register' %}{% endblock %}
{% block ExtraHead %}
    <link rel="stylesheet" href="{% static 'customer/css/register.css' %}">
{% endblock %}
{% block Body %}
    <div class="my-form">
        <form method="post" novalidate style="direction: ltr">
            {% csrf_token %}
            {{ form.as_p }}
            {#        <label for="phone">{% trans 'Phone Number ' %}</label>#}
            {#        {{ form.phone }}<br><br>#}
            {#        <label for="email">{% trans 'Email  ' %}</label>#}
            {#        {{ form.email }}<br><br>#}
            {#        <label for="first_name">{% trans 'First Name  ' %}</label>#}
            {#        {{ form.first_name }}<br><br>#}
            {#        <label for="last_name">{% trans 'Last Name  ' %}</label>#}
            {#        {{ form.last_name }}<br><br>#}
            {#        <label for="password_1">{% trans 'password  ' %}</label>#}
            {#        {{ form.password_1 }}<br><br>#}
            {#        <label for="password_2">{% trans 'confirm password  ' %}</label>#}
            {#        {{ form.password_2 }}<br><br>#}
            <button type="submit">{% trans 'Register' %}</button>
        </form>
        <p id="rl">{% trans "Do you have an account?  " %}<a
                href={% url 'customer:customer_login' %}>{% trans 'Login' %}</a>
    </div>
{% endblock %}