My_Market/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import My_Market.settings as settings
from product.views import *

urlpatterns = i18n_patterns(
    path('', HomeView.as_view(), name='home'),
    path('change-lang/', ChangeLanguageView.as_view(), name='change_lang'),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')),
    path('customer/', include('customer.urls')),
    path('order/', include('order.urls')),
    path('product-api/', include('product.api_urls')),
    path('customer-api/', include('customer.api_urls')),
    path('order-api/', include('order.api_urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    prefix_default_language=True,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from .views import *

app_name = 'order'
urlpatterns = [
    path('', OrderDetailView.as_view(), name='order_detail'),
    path('paid/', PaidOrderDetailView.as_view(), name='paid_order_detail'),
    path('canceled/', CanceledOrderDetailView.as_view(), name='canceled_order_detail'),
    path('add/<int:pk>/', OrderAddView.as_view(), name='order_add'),
    path('add-off-code/', OffCodeAddView.as_view(), name='off_code_add'),
    path('add-quantity/<int:pk>/', AddQuantityView.as_view(), name='add_quantity'),
    path('remove-quantity/<int:pk>/', RemoveQuantityView.as_view(), name='remove_quantity'),
    path('delete-order-item/<int:pk>/', RemoveOrderItemView.as_view(), name='remove_order_item'),
    path('create-order/<int:pk>/', CreateOrderView.as_view(), name='create_order'),
    path('remove-off-code/<int:pk>/', RemoveOffCodeView.as_view(), name='remove_off_code'),
    path('select-address/', SelectAddress.as_view(), name='select_address'),
    path('add-address/', AddressCreateView.as_view(), name='add_address'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('cancel-order/', CancelOrderView.as_view(), name='cancel_order'),
]

order/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.models import *
from product.models import *
from customer.models import *
from .validators import *


# Create your models here.

class Order(BaseModel, TimestampMixin):
    customer = models.ForeignKey(
        Customer,
        on_delete=models.CASCADE,
        verbose_name=_('Customer'),
        help_text=_('customer for this order'),
    )
    off_code = models.ForeignKey(
        OffCode,
        on_delete=models.SET_NULL,
        verbose_name=_('Off Code'),
        help_text=_('Off code for this order'),
        null=True,
        blank=True,
    )
    status = models.CharField(
        choices=(
            ('d', 'during'),
            ('p', 'paid'),
            ('c', 'canceled'),
        ),
        default='d',
        verbose_name=_('Status'),
        help_text=_('Status for this order'),
        max_length=10,
    )
    menu_item_variants = models.ManyToManyField(
        MenuItemVariant,
        through="OrderMenuItem",
        through_fields=(
            'order',
            'menu_item_variant',
        ),
    )
    paid_price = models.IntegerField(
        verbose_name=_('Paid Price'),
        null=True,
        blank=True,
    )

    def pure_price(self):
        price = 0
        for i in self.ordermenuitem_set.all():
            price += (i.menu_item_variant.final_price() * i.quantity)
        return price

    def final_price(self):
        price = self.pure_price()
        if self.off_code:
            final_price = self.off_code.final_price(price)
            return final_price
        else:
            return price

    def __str__(self):
        return f"{self.id}# {self.customer.user.phone} : {self.status} : {self.final_price()}"

    class Meta:
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')


class OrderMenuItem(BaseModel, TimestampMixin):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        verbose_name=_('Order'),
        help_text=_('order'),
    )
    menu_item_variant = models.ForeignKey(
        MenuItemVariant,
        on_delete=models.CASCADE,
        verbose_name=_('Menu Item'),
        help_text=_('menu item'),
    )
    quantity = models.IntegerField(
        verbose_name=_('Quantity'),
        help_text=_('quantity'),
        validators=[quantity_validator]
    )

    def final_price(self):
        return self.menu_item_variant.final_price() * self.quantity

    def __str__(self):
        return f"{self.id}# {self.order}: {self.menu_item_variant} : {self.quantity}"

    class Meta:
        verbose_name = _('OrderMenuItem')
        verbose_name_plural = _('OrderMenuItems')

product/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.models import *
from .validators import *
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager
from django.db.models import Avg, Min, Max
from customer.models import *


# Create your models here.


class Category(BaseModel, TimestampMixin):
    name = models.CharField(
        max_length=50,
        verbose_name=_('Name'),
        help_text=_('Category Name'),
    )
    name_fa = models.CharField(
        max_length=50,
        verbose_name=_('PersianName'),
        null=True,
        blank=True,
    )
    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    is_sub_category = models.BooleanField(
        verbose_name=_('Is sub category?'),
        help_text=_('Is sub category? or main?'),
        default=False,
    )

    def my_delete(self):
        super().my_delete()
        for i in self.category_set.all():
            i.my_delete()

    def __str__(self):
        return f"{self.id}# {self.name}"

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')


class Discount(BaseModel, TimestampMixin):
    is_percent = models.BooleanField(
        default=False,
        verbose_name=_('Is Percent?'),
        help_text=_('Do you want to enter a percentage?'),
    )
    price = models.IntegerField(
        verbose_name=_('Discount Price'),
        help_text=_('Enter the discount price'),
        validators=[price_validator],
        default=0,
    )
    percent = models.FloatField(
        verbose_name=_('Discount Percent'),
        help_text=_('Enter the discount percent'),
        validators=[percent_validator],
        default=0,
    )
    max = models.IntegerField(
        null=True,
        blank=True,
        verbose_name=_('Max Discount Price'),
        help_text=_('Enter the max discount price'),
        validators=[price_validator],
    )
    expire_date_time = models.DateTimeField(
        verbose_name=_('Expire Date'),
        help_text=_('Enter the expire date'),
    )

    def is_expired(self):
        if self.is_deleted:
            return True
        if timezone.now() > self.expire_date_time:
            return True
        return False

    def final_price(self, price):
        if self.is_percent:
            discount = (price * self.percent) // 100
            if self.max:
                if discount > self.max:
                    return price - self.max
                else:
                    return price - discount
            else:
                return price - discount
        else:
            if price > self.price:
                return price - self.price
            else:
                return 0

    def __str__(self):
        if self.is_percent:
            return f"{self.id}# {self.percent}% , max = {self.max} , expire-date = {self.expire_date_time} , {self.is_expired()}"
        else:
            return f"{self.id}# {self.price}$ , max = {self.max} , expire-date = {self.expire_date_time} , {self.is_expired()}"

    class Meta:
        verbose_name = _('Discount')
        verbose_name_plural = _('Discounts')


class OffCode(Discount):
    code = models.CharField(
        verbose_name=_('Off Code'),
        max_length=14,
        validators=[off_code_validator],
        help_text=_('Enter the off code'),
    )

    class Meta:
        verbose_name = _('OffCode')
        verbose_name_plural = _('OffCodes')


""""
    menu item classes
"""


class Brand(BaseModel, TimestampMixin):
    name = models.CharField(
        max_length=30,
        verbose_name=_('brand name'),
        help_text=_('Enter the brand name'),
        # validators=[menu_item_name_validator],
    )
    name_fa = models.CharField(
        max_length=50,
        verbose_name=_('PersianName'),
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = _('Brand')
        verbose_name_plural = _('Brands')


class Image(BaseModel, TimestampMixin):
    image = models.FileField(
        verbose_name=_('menu item image'),
        help_text=_('Enter your image'),
        upload_to='product/menu_items/images/',
    )
    menu_item = models.ForeignKey(
        'MenuItem',
        on_delete=models.CASCADE,
        verbose_name=_('menu item for this image'),
        help_text=_('Enter the menu item for this image'),
    )

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Images')


class Specification(BaseModel, TimestampMixin):
    name = models.CharField(
        max_length=200,
        verbose_name=_('Specification name'),
        help_text=_('Enter the Specification name'),
    )
    name_fa = models.CharField(
        max_length=200,
        verbose_name=_('PersianName'),
        null=True,
        blank=True,
    )
    value = models.CharField(
        max_length=200,
        verbose_name=_('Specification Value'),
        help_text=_('Enter the Specification value'),
    )
    value_fa = models.CharField(
        max_length=200,
        verbose_name=_('PersianValue'),
        null=True,
        blank=True,
    )

    def __str__(self):
        return f"{self.id}# {self.name} : {self.value}"

    class Meta:
        verbose_name = _('Specification')
        verbose_name_plural = _('Specifications')


class VariableSpecification(BaseModel, TimestampMixin):
    name = models.CharField(
        max_length=200,
        verbose_name=_('Specification name'),
        help_text=_('Enter the Specification name'),
    )
    value = models.CharField(
        max_length=200,
        verbose_name=_('Specification Value'),
        help_text=_('Enter the Specification value'),
    )

    def __str__(self):
        return f"{self.id}# {self.name} : {self.value}"

    class Meta:
        verbose_name = _('VariableSpecification')
        verbose_name_plural = _('VariableSpecifications')


class MenuItem(BaseModel, TimestampMixin):
    name = models.CharField(
        max_length=50,
        verbose_name=_('menu item name'),
        help_text=_('Enter the Menu items name'),

    )
    name_fa = models.CharField(
        max_length=50,
        verbose_name=_('PersianName'),
        null=True,
        blank=True,
    )
    category = models.ManyToManyField(
        Category,
        verbose_name=_('menu item category'),
        help_text=_('Choose the menu item stock'),
    )
    brand = models.ForeignKey(
        Brand,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_('menu item brand'),
        help_text=_('Choose the menu item brand'),
    )
    specifications = models.ManyToManyField(
        Specification,
        related_name='menu_items',
    )
    description = RichTextUploadingField(
        verbose_name=_('menu item description'),
        help_text=_('Enter the menu item description'),
        null=True,
        blank=True,
    )
    description_fa = RichTextUploadingField(
        verbose_name=_('PersianDescription'),
        null=True,
        blank=True,
    )

    status = models.BooleanField(
        verbose_name=_('variant status'),
        help_text=_('has variant?'),
        default=False,
    )
    variable_specification_name = models.CharField(
        verbose_name=_('Variable Specification name'),
        help_text=_('variable specification name'),
        max_length=50,
        null=True,
        blank=True,
    )
    variable_specification_name_fa = models.CharField(
        verbose_name=_('Variable Specification persian name'),
        max_length=50,
        null=True,
        blank=True,
    )
    tags = TaggableManager(
        verbose_name=_('Similar specification'),
        help_text=_('for similar product'),
        blank=True,
    )
    favorites_customers = models.ManyToManyField(
        Customer,
        blank=True,
        related_name='favorites',
    )
    sell = models.IntegerField(default=0, verbose_name=_('sell count'))

    def my_delete(self):
        super().my_delete()
        for i in self.menuitemvariant_set.all():
            i.delete_time_stamp = timezone.now()
            i.is_deleted = True
            i.save()
        for i in self.comment_set.all():
            i.delete_time_stamp = timezone.now()
            i.is_deleted = True
            i.save()

    def average_rate(self):
        data = Comment.objects.filter(is_reply=False, menu_item=self).aggregate(avg=Avg('rate'))
        rate = 0
        if data['avg']:
            rate = round(data['avg'], 1)
        return rate

    def __str__(self):
        return f"{self.id}#   {self.name} "

    class Meta:
        verbose_name = _('MenuItem')
        verbose_name_plural = _('MenuItems')


class MenuItemVariant(BaseModel, TimestampMixin):
    menu_item = models.ForeignKey(
        MenuItem,
        on_delete=models.CASCADE,
    )

    price = models.IntegerField(
        verbose_name=_('menu item price'),
        help_text=_('Enter the menu item price'),
        validators=[price_validator],
    )
    count = models.IntegerField(
        verbose_name=_('menu item stock'),
        help_text=_('Enter the menu item stock'),
        validators=[price_validator],
        default=0,
    )
    discount = models.ForeignKey(
        Discount,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_('menu item discount'),
        help_text=_('Enter the menu item discount'),
    )
    variable_specification_value = models.CharField(
        verbose_name=_('Variable Specification Value'),
        help_text=_('variable specification value'),
        max_length=50,
        default=_('Not entered'),
    )
    variable_specification_value_fa = models.CharField(
        verbose_name=_('Variable Specification persian Value'),
        max_length=50,
        null=True,
        blank=True,
    )

order/forms.py
from django import forms
from .models import *

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order

templates/order/add_to_cart.html
{% load i18n %}
{#<form method="post">#}
{#    {#}
{#    <input type="hidden" name="menu_item_variant_id" value={{ menu_item_variant.id }}>#}
{#    <button type="submit" class="btn btn-danger"#}
{#            {% if menu_item_variant.count < 1 or not user.is_authenticated %}disabled{% endif %}>{% trans "Add to cart" %}</button>#}
{#    {% if not user.is_authenticated %}#}
{#        <small>&nbsp;&nbsp;{% trans 'first login' %}</small>#}
{#    {% endif %}#}
{#    {% if menu_item_variant.count < 1 %}#}
{#        <small>&nbsp;&nbsp;{% trans 'not currently available' %}</small>#}
{#    {% endif %}#}
{#</form>#}

<a href="{% url 'order:order_add' menu_item_variant.id %}"
   class="btn btn-danger
   {% if menu_item_variant.count < 1 or not user.is_authenticated %}disabled{% endif %}">{% trans "Add to cart" %}</a>
{% if not user.is_authenticated %}
    <small>&nbsp;&nbsp;{% trans 'first login' %}</small>
{% endif %}
{% if menu_item_variant.count < 1 %}
    <small>&nbsp;&nbsp;{% trans 'not currently available' %}</small>
{% endif %}

templates/order/canceled_detail.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load static %}
{% block Title %}{% trans 'Cart' %}{% endblock %}
{% block ExtraStyle %}
    <style>
        .but-cart {

            width: 150px;


        }

        .div-cart {
            margin: auto;
            text-align: center;
            margin-top: 10rem;
        }

        .c-order-box {
            color: white;
            background-color: darkslateblue;
            margin: auto;
            width: 90%;
            border-radius: 2rem;
            text-align: center;
            height: auto;
            margin-bottom: 2rem;
        }

        .c-order-box img {
            height: 100px;
            width: auto;
            max-width: 100px;
            max-height: 100px;
            margin-bottom: 1rem;
        }

        .c-order-box-in {
            margin: 2rem;
            text-align: center;
        }

        .order-price {
            font-size: 1.5rem;
            color: greenyellow;
        }

    </style>
{% endblock %}
{% block Body %}

    {% if empty %}
        <div style="margin:auto;text-align: center">
            <h1 style="margin:auto;text-align: center;
                    {% if language == 'fa' %}font-family: IRANSans;{% else %}font-family: Andalus;{% endif %}color: #052953">{% trans 'You dont have any canceled orders' %}</h1>
        </div>

    {% else %}
        {% for j in order_canceled %}
            <div class="c-order-box row">

                {% for i in j.ordermenuitem_set.all %}
                    <div class="c-order-box-in col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2">
                        <img src="{% static i.menu_item_variant.menu_item.image_set.last.image %}">
                        <p>
                            {% if language == 'fa' %}
                                {% if i.menu_item_variant.menu_item.name_fa %}
                                    {{ i.menu_item_variant.menu_item.name_fa }}
                                {% else %}
                                    {{ i.menu_item_variant.menu_item.name }}
                                {% endif %}
                            {% else %}
                                {{ i.menu_item_variant.menu_item.name }}
                            {% endif %}

                        </p>
                        <p>{% trans 'quantity :' %}&nbsp;{{ i.quantity }}</p>
                        <p>{% trans 'final price : ' %}&nbsp;{{ i.final_price }}</p>
                    </div>
                {% endfor %}


                <p class="order-price">{% trans 'Final Price :' %}&nbsp;{{ j.paid_price }}&nbsp;{% trans 'Toman' %}</p>
            </div>
        {% endfor %}

        <div class="row pag">
            {% include 'base/pagination.html' with menu_items=order_canceled %}
        </div>
    {% endif %}

    <div class="div-cart">
        <a class="btn btn-primary but-cart" href="{% url 'order:paid_order_detail' %}">{% trans 'paid' %}</a>
        <a class="btn btn-primary but-cart" href="{% url 'order:order_detail' %}">{% trans 'Cart' %}</a>
    </div>

{% endblock %}

templates/order/create_order.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load static %}
{% block Title %}{% trans 'Create Order' %}{% endblock %}
{% block ExtraStyle %}
    <style>
        .c-order-box {
            color: white;
            background-color: darkslateblue;
            margin: auto;
            width: 90%;
            border-radius: 2rem;
            text-align: center;
            height: auto;
        }

        .c-order-box img {
            height: 100px;
            width: auto;
            max-width: 100px;
            max-height: 100px;
            margin-bottom: 1rem;
        }

        .c-order-box-in {
            margin: 2rem;
            text-align: center;
        }

        .off-code {
            margin: auto;
            text-align: center;
        }

        .off-code form {
            margin-top: 3rem;
        }

        .off-code form input {
            border-radius: 5px;
            border: 8px solid transparent;
            background-color: #fff22b;
            text-align: center;

        }

        .off-code form input:focus {
            background-color: white;

        }

        .order-price {
            font-size: 1.5rem;
            color: greenyellow;
        }

        .off-code-del {
            margin: auto;
            text-align: center;
        }

        .off-code-del small {
            font-size: 1rem;

        }

        .off-code-del a {
            font-size: 1rem;
            background-color: transparent;
            color: red;
            border: 0;
        }

        .next-form {
            margin: auto;
            text-align: center;
            margin-top: 3rem;
        }

    </style>
{% endblock %}
{% block Body %}
    <div class="c-order-box row">
        {% for i in order.ordermenuitem_set.all %}
            <div class="c-order-box-in col-12 col-sm-6 col-md-4 col-lg-3 col-xl-2">
                <img src="{% static i.menu_item_variant.menu_item.image_set.last.image %}">
                <p>
                    {% if language == 'fa' %}
                        {% if i.menu_item_variant.menu_item.name_fa %}
                            {{ i.menu_item_variant.menu_item.name_fa }}
                        {% else %}
                            {{ i.menu_item_variant.menu_item.name }}
                        {% endif %}
                    {% else %}
                        {{ i.menu_item_variant.menu_item.name }}
                    {% endif %}

                </p>
                <p>{% trans 'quantity :' %}&nbsp;{{ i.quantity }}</p>
                <p>{% trans 'final price : ' %}&nbsp;{{ i.final_price }}</p>
            </div>
        {% endfor %}
        {% if order.off_code %}
            {% if not order.off_code.is_expired %}
                <p class="order-price" style="text-decoration: line-through;color: red">
                    {% trans 'Pure Price : ' %}&nbsp;{{ order.pure_price }}&nbsp;{% trans ' Toman' %}</p>
                <p class="order-price">{% trans 'Final Price :' %}&nbsp;{{ order.final_price }}&nbsp;{% trans 'Toman' %}</p>
            {% else %}
                <p class="order-price">{% trans 'Final Price :' %}&nbsp;{{ order.final_price }}&nbsp;{% trans 'Toman' %}</p>
            {% endif %}
        {% else %}
            <p class="order-price">{% trans 'Final Price :' %}&nbsp;{{ order.final_price }}&nbsp;{% trans 'Toman' %}</p>
        {% endif %}
    </div>
    <div class="off-code">
        <form method="post" action="{% url 'order:off_code_add' %}">
            {% csrf_token %}
            <input type="text" name="off_code" placeholder="{% trans 'Off Code' %}" required>
            <input type="hidden" name="order_id" value={{ order.id }}>
            <button type="submit" class="btn btn-dark">{% trans 'Submit' %}</button>
        </form>
        {% if order.off_code %}
            {% if not order.off_code.is_expired %}
                <div class="off-code-del">
                    <small>{{ order.off_code.code }}&nbsp;&nbsp;</small>
                    <a href="{% url 'order:remove_off_code' order.id %}" class="btn">{% trans 'delete' %}</a>
                </div>
            {% endif %}
        {% endif %}
    </div>
    <div class="next-form">
        <form method="post" action="{% url 'order:cancel_order' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">{% trans 'Cancel' %}</button>
        </form>
    </div>
    <div class="next-form">
        <form method="post" action="{% url 'order:select_address' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">{% trans 'next level' %}&nbsp;&nbsp;--></button>
        </form>
    </div>
{% endblock %}

templates/order/order.html
{% extends 'base/base.html' %}
{% load i18n %}
{% load static %}
{% block Title %}{% trans 'Cart' %}{% endblock %}
{% block ExtraHead %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
{% endblock %}
{% block ExtraStyle %}
    <style>
        .but-cart {

            width: 150px;


        }

        .div-cart {
            margin: auto;
            text-align: center;
            margin-top: 10rem;
        }

        .order-box {
        {#color: white;#} color: black;
        {#background-color: darkslateblue;#} background-color: #c2d605;
            height: 200px;
            text-align: center;
            margin: auto;
            margin-bottom: 3rem;
            width: 90%;
            border-radius: 15px 0 15px 0;
        }

        .order-img {
            height: 90%;
            width: auto;
            max-width: 150px;
            margin: 1rem;
            max-height: 180px;
        }

        .menu-item-name {
            font-size: 1rem;
            margin-top: 4rem;
        }

        .zarb {
            border-radius: 100%;
            background-color: red;
            color: white;
            margin-top: 3.8rem;
        }

        .zarb:hover {
            background-color: white;
            color: red;
        }

        .zarb:active {
            background-color: brown;
            color: white;
        }

        .order-icon {
            margin-top: 1.5rem;
            font-size: 1.5rem;

        }

        .order-icon.order-plus {
            color: #01a401;
        }

        .order-icon.order-min {
            color: #ff1313;
        }

        span.order-icon {
            margin-top: 6rem;

        }

        @media screen and (max-width: 1200px) {
            #order-item-name {
                display: none;

            }
        }

        .c-order-btn {
            width: 80%;
            margin: auto;
            text-align: center;
        }

        .c-order-btn a {
            width: 20%;
            margin: auto;
            font-size: 2rem;
            font-family: Andalus;
        }

        @media screen and (max-width: 620px) {
            #order-item-name {
                display: block;

            }

            #order-item-img {
                display: none;
            }

            .order-icon {
                margin-top: 1.5rem;
                font-size: 1rem;

            }
        }
    </style>
{% endblock %}
{% block Body %}

    {% if empty %}
        <div style="margin:auto;text-align: center">
            <h1 style="margin:auto;text-align: center;{% if language == 'fa' %}font-family: IRANSans;{% else %}font-family: Andalus;{% endif %}color: #052953">{% trans 'Your Cart Is Empty' %}</h1>
        </div>
    {% else %}

        {% for j in order_during %}
            <div class="row">
                <div class="order-box">
                    <div class="row">
                        <div class="col-2">
                            <form method="post" action="{% url 'order:remove_order_item' j.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn zarb">X</button>
                            </form>
                        </div>
                        <div class="col-2">
                            <p class="menu-item-name">{% trans 'Price :' %}&nbsp;&nbsp;{{ j.final_price }}</p>
                        </div>
                        <div class="col-5 col-sm-4">
                            <div class="order-icon order-min btn">
                                <form method="post" action="{% url 'order:remove_quantity' j.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="order-icon order-min btn"><i
                                            class="fa fa-minus  "></i></button>
                                </form>
                            </div>
                            <small id="quantity-small" class="order-icon">{{ j.quantity }}</small>
                            <div class="order-icon order-plus btn">


                                <form method="post" action="{% url 'order:add_quantity' j.id %}">

                                    {% csrf_token %}

                                    <button type="submit"
                                            class="order-icon order-plus btn {% if j.menu_item_variant.count < 1 %}disabled{% endif %}">
                                        <i
                                                class="fa fa-plus  "></i></button>

                                </form>


                            </div>

                        </div>
                        <div class="col-1 col-sm-2" id="order-item-name">
                            <p class="menu-item-name">
                                {% if language == 'fa' %}
                                    {% if j.menu_item_variant.menu_item.name_fa %}
                                        {{ j.menu_item_variant.menu_item.name_fa }}
                                    {% else %}
                                        {{ j.menu_item_variant.menu_item.name }}
                                    {% endif %}
                                {% else %}
                                    {{ j.menu_item_variant.menu_item.name }}
                                {% endif %}

                            </p>
                        </div>
                        <div class="col-1 col-sm-2" id="order-item-img">
                            <img class="order-img"
                                 src="{% static j.menu_item_variant.menu_item.image_set.last.image %}">
                        </div>
                    </div>

                </div>
            </div>
        {% endfor %}
        <div class="c-order-btn">

            <a href="{% url 'order:create_order' pk=order_during.last.order.id %}" class="btn btn-success "
               style="{% if language == 'fa' %}font-family: IRANSans;{% else %}font-family: Andalus;{% endif %}">
                {% trans 'create order' %}
            </a>
        </div>

        {#        <div class="row pag">#}
        {#            {% include 'base/pagination.html' with menu_items=order_during %}#}
        {#        </div>#}
    {% endif %}

    <div class="div-cart">
        <a class="btn btn-primary but-cart" href="{% url 'order:canceled_order_detail' %}">{% trans 'canceled' %}</a>
        <a class="btn btn-primary but-cart" href="{% url 'order:paid_order_detail' %}">{% trans 'paid' %}</a>
    </div>

    {#    <script>#}
    {#        function add_quantity(id) {#}
    {##}
    {#            $.ajax(#}
    {#                {#}
    {##}
    {#                    'url': 'http://127.0.0.1:8000/order-api/order-menu-item-detail/' + id,#}
    {#                    'type': 'patch',#}
    {#'data': $('#add_quantity').serialize(),#}
    {#                    'data': {'quantity': (Number($('#quantity-input').val()) + 1)},#}
    {#                    'headers': {#}
    {#                        'X-CSRFToken': '{{ csrf_token }}',#}
    {#                    },#}
    {#                    success: function (resp, status) {#}
    {#                        $('#quantity-small').innerText = '';#}
    {#                        $('#quantity-small').innerText = resp['quantity'];#}
    {#                        console.log(resp)#}
    {#                        alert((resp['quantity']))#}
    {##}
    {#                    }#}
    {#                }#}
    {#            )#}
    {#        }#}
    {#    </script>#}
{% endblock %}